version: '3.8'

services:
  flask-app:
    build: .
    container_name: translator-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      OLLAMA_URL: "http://ollama:11434/api/chat"

  ollama:
    image: ollama/llama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
